title = "Climate, Human, Data & Modeling"
baseURL = "https://zhang-beichen.github.io/"
# The theme will be loaded via the module import below
paginate = 10
enableRobotsTXT = true
mainSections = ["posts"]   # adapt to your content folders

[outputs]
  home = ["HTML", "RSS", "JSON"]   # JSON later used by search (optional)

[taxonomies]
  tag = "tags"
  category = "categories"

[module]
  [[module.imports]]
    path = "github.com/janraasch/hugo-bearblog"   # Bear Blog theme
    # Pin a specific tag or commit for stability once you pick one:
    # version = "v<tag>"  # e.g., v1.0.0 (replace with a real tag when chosen)

[menu]
  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 1

  [[menu.main]]
    name = "Research"
    url  = "/research/"
    weight = 2

  [[menu.main]]
    name = "Blog"
    url  = "/posts/"
    weight = 3

  [[menu.main]]
    name = "Playground"
    url  = "/playground/"
    weight = 4

  [[menu.main]]
    name = "Contact Me"
    url  = "/contact_me/"
    weight = 5

[params]
  description = "Postdoc • Climate & AI"
  # Set site-wide math to true if most pages need it; otherwise enable per-page
  math = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # don't escape html - render it directly
